### PR TITLE
Fix typo in README.

### PR DESCRIPTION
**Pull request by DRosadoYew**

### CODE REVIEW

**Comment by tonyarnold** [comment]
Sorry to digress for a moment @DRosadoYew --

:point_up: Did anyone setup @codecov-io explicitly? If not, that's a new level of GitHub spam…

**Comment by srdanrasic** [comment]
@DRosadoYew, thanks for the fix.

@tonyarnold, yep, I disabled per-commit notifications now.

**Comment by tonyarnold** [comment]
@srdanrasic no worries. If it's useful, don't turn it off on my account — I've just seen some "pushing" of code coverage services into repos (usually it's via a PR though).

**Comment by srdanrasic** [comment]
@tonyarnold I've left them for PRs, disabled for each commit.

**Pull request merged**
