### PR TITLE
Enable Travis CI

### PR DESCRIPTION
**Pull request by ivanmoskalev**
I suggest we experiment with CI. I have added a Travis makefile, and would like to setup a Travis project for Bond. @srdanrasic, could you please do that? We can experiment in this PR.

### CODE REVIEW

**Comment by srdanrasic** [comment]
That's a good idea. I tried to setup Travis few months ago but had some issues and not enough time to fix it.

I've linked the account and added repository: https://travis-ci.org/SwiftBond/Bond

I guess you should do some dummy commit to this PR in order to trigger it.

**Comment by srdanrasic** [comment]
I might be wrong, but it appears that Travis supports XCode only up to v6.1...

**Comment by tonyarnold** [comment]
No, they added Xcode 6.4 support today: https://twitter.com/travisci/status/616007115832999936

**Comment by srdanrasic** [comment]
That's great. Thanks @tonyarnold

**Comment by ivanmoskalev** [comment]
I think I fixed it, guys. Please don't merge before I squash the branch

**Comment by ivanmoskalev** [comment]
We are good to go!

**Comment by srdanrasic** [comment]
Great! Is it possible to test BondOSX scheme too?

**Comment by srdanrasic** [comment]
Thanks Ivan.

**Pull request merged**
