### PR TITLE
Swift 2.0, Xcode beta 2 support

### PR DESCRIPTION
**Pull request by sync**
:warning: probably doesn't belong in master :warning: 

you could create a swift 2.0 branch

### CODE REVIEW

**Comment by srdanrasic** [comment]
Thanks @sync. Did Beta 2 fix that ABI compatibility error?

**Comment by sync** [comment]
Yes it did, sorry I should have mentioned this

**Comment by srdanrasic** [comment]
That's great. I've created swift-2.0 branch. Could you try doing PR into that branch?

**Comment by sync** [comment]
Doing this now

**Pull request closed without merging**
