### PR TITLE
Add global function to merge array of EventProducers

### PR DESCRIPTION
**Pull request by manas-chaudhari**
For #195 

I couldn't find any tests for merge/combineLatest. Please suggest where I can write tests if required.

### CODE REVIEW

**Comment by manas-chaudhari** [comment]
@srdanrasic Have updated the implementation as per our discussion

**Comment by srdanrasic** [comment]
Thanks @manas-chaudhari. I still think that we should call this `combineLatest` to be consistent with other FRP frameworks out there.

**Comment by manas-chaudhari** [comment]
I referred these links:
- http://reactivex.io/documentation/operators/merge.html
- http://reactivex.io/documentation/operators/combinelatest.html

Here's my understanding:
- Combine transforms the multiple values from different signals into a single value. The transform is must for combining into a single value. In case of SwiftBond, I see that the transform function has been omitted  and we always use `combining into a tuple` as the transform.
- Merge requires that values be of same type and it simply `merges` them.

Equivalent methods in RxJava:
- [CombineLatest](http://reactivex.io/RxJava/javadoc/rx/Observable.html#combineLatest(java.util.List,%20rx.functions.FuncN))
- [Merge](http://reactivex.io/RxJava/javadoc/rx/Observable.html#merge(java.lang.Iterable))

Based on these, I think `merge` fits better. @srdanrasic: Let me know what you think

**Comment by srdanrasic** [comment]
You are right :) I'll merge this.

**Pull request merged**
