### PR TITLE
Batch updates

### PR DESCRIPTION
**Pull request by tonyxiao**
This set of changes is likely to be much more controversial. However the motivation is that in order to be performant at scale the ability to batch changes and animate together instead of animating each change one at a time is gonna be pretty critical. I particular I expect the `beginBatchUpdates` and `endBatchUpdates` functions to be called from Core Data `NSFetchedResultsController`. I did add a lot more test and verity that it works in a real application and followed the implementation pattern, but I also understand the difficulty of adding to API surface.

### CODE REVIEW

**Comment by tonyxiao** [comment]
Also it looks like since I last checked there are now merge conflicts. Will resolve and update the PR.

**Comment by tonyarnold** [comment]
Sounds like this addresses my issue #95.

**Comment by srdanrasic** [comment]
@tonyxiao, that you for this improvement. I've resolved the conflicts and will merge it after additional review.

**Comment by srdanrasic** [comment]
Array have been completely revisited in v4. They now have support for batch updates. Thanks anyway!

**Pull request closed without merging**
