### PR TITLE
Merged master into swift-2.0 and applied Xcode 7 beta 4 fixes

### PR DESCRIPTION
**Pull request by mattijsf**
Merged master into swift-2.0 branch and applied Xcode 7 beta 4 compatibility fixes

### CODE REVIEW

**Comment by ivanmoskalev** [comment]
I think we should rebase `swift-2.0` on top of `develop`, not merge the latter into the former.

**Comment by mattijsf** [comment]
Ah yes! ugh Why didn't I see that ;) Shall I close / remove this one then?

**Comment by ivanmoskalev** [comment]
cc/ @srdanrasic
@mattijsf I think you can just close it, I have opened #115. Hope we can do it today :)

**Comment by srdanrasic** [comment]
Yes, we should rebase it. I'll close this. @ivanmoskalev would you like to do that?

**Pull request closed without merging**
